### ISSUE TITLE
Rust bindings for liboepcie

### ISSUE THREAD

**Issue by imalsogreg** [jonnew/open-ephys-pcie#13]
An interface to this beloved language is sorely needed! (feel free to assign to me)

**Comment by jonnew** [comment]
Greg, I'm so sorry for taking so long to respond to this generous issue. There is currently no acquisition software written in rust, that I'm aware of. However, if we had this binding it might inspire that to change.   So, I would love to have this so long as it does not become a maintenance issue.I also would love to learn the language better so maybe you could help me with that via this effort. So, PR away -- I'm excited :).

**Comment by jonnew** [comment]
I'm closing this until there is a re-invigoration!
